keys:
  - &users '':
      - &mario age1n7q58m5ayf3vn3vm465nrqm2v925dku8a066tfzqvmqd42ezcp5qud43pm
  - &hosts '':
      - &winterfell age1ghexn9y0540mdac9ncfgzg98uz5gh9h44gfjppx9z6pjqep5yv3slrc63y
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *winterfell
          - *mario
  - path_regex: secrets/winterfell/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *winterfell
          - *mario
